language: node_js
node_js:
  - 12
script:
  - npm run build
branches:
  only:
  - master    # 构建的分支
cache:
  directories:
  - node_modules # 依赖缓存的目录
before_install:
- export TZ='Asia/beijing'  # 设置时区
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  target-branch: gh-pages
  on:
    branch: master