language: node_js
node_js:
  - 12
install:
  - npm install
os:
  - linux
# script:
#   - npm publish --access=public
branches:
  only:
    - master # 构建的分支
# cache:
#   directories:
#   - node_modules # 依赖缓存的目录
# before_install:
# - export TZ='Asia/beijing'  # 设置时区
deploy:
  provider: npm
  skip_cleanup: true
  email: mahaichao1030@qq.com
  api_key: $NPM_TOKEN
  on:
    branch: master
